### ISSUE TITLE
Error: value.equals is not a function

### ISSUE THREAD

**Issue by OliverXH** [playcanvas/playcanvas-observer#10]
Error: value.equals is not a function:
```js
if (value.equals(node._data[key]) && !force) return false;
```

Here is my code:
```js
const observerData = {
    progress: 30,
    position: [0, 0, 0]
};
const observer = new Observer(observerData);
const history = new History();

let pos = new VectorInput({
    placeholder: ['X', 'Y', 'Z'],
    precision: 3,
    step: 0.05,
    binding: new BindingTwoWay({
        history
    })
});
pos.link(observer, 'position');
container.append(pos);

observer.set('position', [0, 10, 0]);
observer.set('progress', 50);
```
And I can't find `Array.prototype.equals` :
![image](https://user-images.githubusercontent.com/49978259/153816597-1249a054-7142-4126-8392-7d978d0339ca.png)

Is there any solution? Or I need to impliment `equals` by myself?

**Comment by slimbuck** [comment]
Ahh nasty. This is polyfilled by [editor-api](https://github.com/playcanvas/editor-api/blob/main/src/polyfills.js), but this should probably moved to observer. You can add the polyfill to your app in the meantime. Sorry for the trouble!
